version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-linkUp
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
