version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-linkUp
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    environment:
      - DOMAIN=linkupcloud.com
      - CERT_NAME=linkupcloud_cert

  cert_generator:
    image: alpine:latest
    container_name: cert-generator
    volumes:
      - ./ssl:/etc/nginx/ssl
    entrypoint: sh -c "apk add --no-cache openssl && openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/nginx/ssl/key.pem -out /etc/nginx/ssl/cert.pem -days 365 -subj '/CN=${DOMAIN}'"
